// @generated by scripts/generate-codex-consumer-types.mjs — do not edit by hand

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CapabilityManifest {
    pub schema_version: String,
    pub generated_at: String,
    pub server: ServerIdentity,
    pub compatibility: CompatibilityRange,
    pub capabilities: Vec<CapabilityDeclaration>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerIdentity {
    pub protocol_version: String,
    pub build_version: String,
    pub commit: String,
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CompatibilityRange {
    pub minimum_client_protocol: String,
    pub maximum_client_protocol: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CapabilityDeclaration {
    pub id: String,
    pub version: String,
    pub status: CapabilityStatus,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub experimental: bool,
    pub methods: MethodSet,
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub limits: HashMap<String, serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<StructuredReason>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MethodSet {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub client_requests: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub server_requests: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub notifications: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StructuredReason {
    pub code: String,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remediation: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum CapabilityStatus {
    #[serde(rename = "supported")]
    Supported,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "incompatible")]
    Incompatible,
    #[serde(rename = "experimental")]
    Experimental,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeaturePolicy {
    pub schema_version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub features: Vec<FeaturePolicyEntry>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeaturePolicyEntry {
    pub id: String,
    pub capability_id: String,
    pub minimum_capability_version: String,
    pub allowed_statuses: Vec<CapabilityStatus>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requires_explicit_enable: Option<bool>,
}

pub const FEATURE_POLICY_FEATURE_IDS: &[&str] = &[
    "shell.initialize",
    "task.threadLifecycle",
    "task.turnControl",
    "task.approvals",
    "profile.multiWorkspace",
    "studio.providers",
    "studio.skillsList",
    "studio.mcpStatus",
    "studio.multiAgent",
];
